### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by 0xjjad** [frappe/mail#23]
Hello i just installed it using this commands. 

Install Frappe Mail:

bench get-app mail
Create a site with the mail app:

bench --site sitename.localhost install-app mail
Open the site in the browser:

bench browse sitename.localhost --user Administrator

 --
now i can access my website mail with my ip.com/mail 

but its not working, i cant receive any email also cant send/compose an email. send button not working. 

is the frappe mail, working or not yet?

**Comment by s-aga-r** [comment]
@0xjjad This app is a client. You also need to set up mail agents to send and receive emails. 

ref: https://github.com/frappe/mail/pull/21
