### ISSUE TITLE
help

### ISSUE THREAD

**Issue by 0xjjad** [frappe/mail#24]
can i use my website email host ? 

for exmaple my website is websitecompany.com, can i use my email as tech@websitecompany.com ? 
just want to use the app mail client, how to set it up? 

i already configure the Incoming server (IMAP) and Outgoing server (SMTP). 

what else? 
![Screenshot 2024-10-28 at 10 41 52 PM](https://github.com/user-attachments/assets/5997f9f7-1c5f-4a42-9f35-d2c8d97f2fd7)

**Comment by s-aga-r** [comment]
@0xjjad You can follow this to self-host https://github.com/frappe/mail/pull/21
